# Settings for development environment

#theme: "lone-wolf-theme"

url: http://localhost:4000

comments:
  provider: false # "disqus" # false (default), "disqus", "custom"
  disqus:
    shortname: ""

webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""

analytics:
  provider: false # false (default), "google-gtag", "custom"
  google:
    tracking_id: ""
    anonymize_ip: false # true, false (default)
